### ISSUE TITLE
MidasCivil_Toolkit: When using the CombineTextFile function omit text files that do not contain information

### ISSUE THREAD

**Issue by peterjamesnugent** [BHoM/MidasCivil_Toolkit#112]
This issue normally only occurs when the push function returns a null. Section files get created but are blank, and this returns an error in MidasCivil.

It should just be a simple `ReadSection()` and check whether the returned `List<string>` contains any information.

**Comment by Tom-Kingstone** [comment]
During review of historic issues, this issue has already been completed by #117, but was erroneously reopened despite being resolved properly and merged.
