### ISSUE TITLE
COMBINED.mct fails to parse when REBAR-MATL-CODE is included with nodes

### ISSUE THREAD

**Issue by peterjamesnugent** [BHoM/MidasCivil_Toolkit#180]
#### Description:

When combining an existing MCT with pushed BHoM objects the MCT Command Shell in MidasCivil does not like the REBAR-MATL-CODE (which is given by default if you MCT export a blank file).

> Error has been encountered during the data input. : *The command of REBAR-MATL-CODE cannot be executed when nodes or sections are included in the model.
> Run Error : command in line 8-10

#### Steps to reproduce:

1. Export a blank .mcb file 
2. Run MidasCivil Adapter
3. Push a Node
4. Run CombineTextFile()
5. Attempt to load in to MidasCivil

#### Expected behaviour:

No error when loading COMBINED.MCT in to MidasCivil.

**Comment by KalleEdstroem** [comment]
https://github.com/BHoM/MidasCivil_Toolkit/blob/f067ccf7eff10eee920440f4e7da1f2f53e55869/MidasCivil_Engine/Compute/CombineTextFiles.cs#L154-L167

In this bit of code we are adding the `typeNames` that are matching `independents`. 
(Taking these away from `typeNames` after)

But just some lines down.

https://github.com/BHoM/MidasCivil_Toolkit/blob/f067ccf7eff10eee920440f4e7da1f2f53e55869/MidasCivil_Engine/Compute/CombineTextFiles.cs#L228-L240

We are doing the same for all strings in `typeNames`.

**Comment by KalleEdstroem** [comment]
The issue is only present when pushing to a Midas model with existing nodes or sections (as the error message in Midas states). 
If pushed to an empty Midas model I do not get the error. The command with the `REBAR-MATL-CODE` runs before any other elements gets created.
