### ISSUE TITLE
Determine units from *UNIT file for results conversion

### ISSUE THREAD

**Issue by peterjamesnugent** [BHoM/MidasCivil_Toolkit#207]
#### Description:

Use Localisation_Toolkit to handle unit conversion.

Make sure to update dependencies.

**Comment by StephennipBH** [comment]
I have updated the MidasCivil and Bhom Relation Wiki Page. While I was working on the conversion, I realised there is an option to change all units in MidasCivil. Would we be able to add a step of changing Midas units aligning with the SI units in Bhom when we pull results ?

**Comment by peterjamesnugent** [comment]
@StephennipBH my thinking was to read the *UNITS file and write a number of converts to SI units (e.g. kN to N) which can be called in the result conversions.

**Comment by peterjamesnugent** [comment]
Moved to Priority 3 following discussion with to allow time to complete the work on the Localisation_Toolkit: https://github.com/BHoM/Localisation_Toolkit/issues/18

**Comment by peterjamesnugent** [comment]
*UNIT    ; Unit System
; FORCE, LENGTH, HEAT, TEMPER
   N    , M, CAL, C

*UNIT    ; Unit System
; FORCE, LENGTH, HEAT, TEMPER
   KN   , CM, KCAL, C

*UNIT    ; Unit System
; FORCE, LENGTH, HEAT, TEMPER
   KGF  , MM, J, C

*UNIT    ; Unit System
; FORCE, LENGTH, HEAT, TEMPER
   TONF , FT, KJ, C

*UNIT    ; Unit System
; FORCE, LENGTH, HEAT, TEMPER
   LBF  , IN, BTU, C

*UNIT    ; Unit System
; FORCE, LENGTH, HEAT, TEMPER
   KIPS , IN, BTU, F
