### ISSUE TITLE
FEMesh objects not pushing to MidasCivil despite having only 4 nodes

### ISSUE THREAD

**Issue by calumlockhart-bh** [BHoM/MidasCivil_Toolkit#254]
#### Description:

Unable to push a collection of `FEMesh`.

#### Steps to reproduce:

Create `FEMesh`, Push to Midas

#### Expected behaviour:

`FEMesh` to be pushed successfully to midas.

#### Test file(s):

https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/01_Issue/BHoM/MidasCivil_Toolkit/%23254-Push_Mesh_to_MIdas?csf=1&web=1&e=qwLGjN

Setup as shown below
![Setup](https://user-images.githubusercontent.com/55385899/94262316-32d94d80-ff2b-11ea-89a6-49e7592e6673.PNG)

**Comment by peterjamesnugent** [comment]
@calumlockhart-bh is this still an issue?

**Comment by calumlockhart-bh** [comment]
@peterjamesnugent  There are still a number of issues, particularly with panels made of three nodes.

**Comment by peterjamesnugent** [comment]
Can you upload a script with the `FEMesh` elements you are trying to push?

What error messages are you getting?

**Comment by calumlockhart-bh** [comment]
@peterjamesnugent 

I get an error stating that I am trying to push a mesh with more than four nodes.


![image](https://user-images.githubusercontent.com/55385899/109791586-82265700-7c0a-11eb-8dc7-a7aa05754df5.png)

despite

![image](https://user-images.githubusercontent.com/55385899/109791646-94a09080-7c0a-11eb-8e17-73514a7386fc.png)


https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/01_Issue/BHoM/Push_Mesh_to_MIdas?csf=1&web=1&e=5KNKeB

**Comment by calumlockhart-bh** [comment]
(using the latest beta 4.0)

**Comment by calumlockhart-bh** [comment]
![image](https://user-images.githubusercontent.com/55385899/109794233-8f911080-7c0d-11eb-8e0a-fd105242bec0.png)


When using a more complex method to push you can finally push it in to midas, however there are a number of missing meshes.



![image](https://user-images.githubusercontent.com/55385899/109793902-26a99880-7c0d-11eb-9bc2-af1c8244d6f7.png)

**Comment by calumlockhart-bh** [comment]
Have also uploaded the script with the more complex method of splitting the mesh here: 

https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/01_Issue/BHoM/MidasCivil_Toolkit/%23254-Push_Mesh_to_MIdas?csf=1&web=1&e=kjhIPw
