### ISSUE TITLE
Add support for custom sections

### ISSUE THREAD

**Issue by peterjamesnugent** [BHoM/MidasCivil_Toolkit#332]

**Comment by mriquBH** [comment]
*SECT-PSCVALUE    ; Composite General
SECT=   iSec, Type_of_section, Name, CC, 0, 0, 0, 0, 0, 0, YES, NO, Shape, YES, YES
       Area, Asy, Asz, Ixx, Iyy, Izz
       Cyp, Cym, Czp, Czm, Qyb, Qzb, Peri:O, Peri:I, Cent:y, Cent:z
       y1, z1, y2, z2, y3, z3, y4, z4
       OPOLY=y1, z1, y2, z2, y3, z3, y4, z4,...
       IPOLY=y1, z1, y2, z2, y3, z3, y4, z4,...
       .
       .
       .
       .

**Comment by SeanDean85** [comment]
SECT=   2, VALUE     , Costume_W16       , CC, 0, 0, 0, 0, 0, 0, YES, NO, GEN, YES, YES
Area, Asy, Asz, Ixx, Iyy, Izz
Cyp, Cym, Czp, Czm, Qyb, Qzb, Peri:O, Peri:I, Cent:y, Cent:z
y1, z1, y2, z2, y3, z3, y4, z4
OPOLY=y1, z1, y2, z2, y3, z3, y4, z4,...
IPOLY=y1, z1, y2, z2, y3, z3, y4, z4,...

**Comment by mriquBH** [comment]
Costume COMPOSITE - GENERAL
SECT=iSEC, TYPE, SNAME, [OFFSET], bSD, bWE, SHAPE, bBU, bEQ, BPRT
       PART=part_num 
       AREA, ASy, ASz, Ixx, Iyy, Izz
       Cyp, Cym, Czp, Czm, Qyb, Qzb, PERI_OUT, PERI_IN, Cy, Cz
       Y1, Y2, Y3, Y4, Z1, Z2, Z3, Z4Area, Asy, Asz, Ixx, Iyy, Izz
       OPOLY=X1, Y1, X2, Y2, ..., Xn, Yn
       IPOLY=X1, Y1, X2, Y2, ..., Xn, Yn

       PART=part_num 
       AREA, ASy, ASz, Ixx, Iyy, Izz
       Cyp, Cym, Czp, Czm, Qyb, Qzb, PERI_OUT, PERI_IN, Cy, Cz
       Y1, Y2, Y3, Y4, Z1, Z2, Z3, Z4Area, Asy, Asz, Ixx, Iyy, Izz
       OPOLY=X1, Y1, X2, Y2, ..., Xn, Yn
       IPOLY=X1, Y1, X2, Y2, ..., Xn, Yn
       ...
